project:
  type: website
  output-dir: docs

website:
  title: "Thao Nguyen"
  navbar:
    background: "#b1c9db"
    foreground: "#FFFFFF"
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Explore"
        href: explore.qmd
    right: 
      - icon: linkedin
        href: https://www.linkedin.com/in/thao-nguyen-5b1088219/
      - icon: github
        href: https://github.com/thanhthao293

format:
  html:
    theme: journal
    css: styles.css
    toc: true

editor: visual


