project:
  type: website
  output-dir: docs

website:
  title: "Thao Nguyen"
  favicon: logo.png
  navbar:
    title: false
    logo: logo.png
    background: "#b1c6d5"
    foreground: "#FFFFFF"
    left:
      - text: "About"
        href: index.qmd
      - text: "Explore"
        href: explore.qmd
      - text: "Resume"
        href: Resume.pdf
        target: _blank
    right: 
      - icon: linkedin
        href: https://www.linkedin.com/in/thao-nguyen-5b1088219/
      - icon: github
        href: https://github.com/thanhthao293

      

format:
  html:
    theme: journal
    css: styles.css
    toc: true

editor: visual


