project:
  type: website
  output-dir: docs

website:
  title: "Thao Nguyen"
  favicon: logo.png
  navbar:
    title: "Thao Nguyen"
    logo: logo.png
    right: 
      - text: "About"
        href: index.qmd
      - text: "Explore"
        href: explore.qmd
      - text: "Resume"
        href: Resume.pdf
        target: _blank
      - icon: linkedin
        href: https://www.linkedin.com/in/thao-nguyen-5b1088219/
      - icon: github
        href: https://github.com/thanhthao293
  page-footer:
    left: © 2024 Thao Nguyen
    
    
format:
  html:
    theme: 
      light: [journal, styles.scss]
      dark: [journal, dark-theme.scss]
    toc: true
    toc-title: Table of Contents
    toc-location: left
    page-layout: full

editor: visual


