project:
  type: website
  output-dir: docs

website:
  title: "Thao Nguyen"
  navbar:
    left:
      - text: "about me"
        href: about.qmd
      - text: "explore"
        href: explore.qmd

format:
  html:
    theme: journal
    css: styles.css
    toc: true

editor: visual

